version: "2"

run:
  timeout: 5m
  tests: true

output:
  sort-results: true

linters-settings: {}
#   gocyclo:
#     min-complexity: 15
#   govet:
#     enable-all: true
#     disable:
#       - fieldalignment
#   lll:
#     line-length: 120
#     tab-width: 2
#   revive:
#     rules:
#       - name: exported
#       - name: indent-error-flow
#       - name: if-return
#       - name: range
#       - name: var-declaration
#       - name: var-naming
#         arguments:
#           - ["ID", "JSON", "SARIF", "YAML", "CLI", "HTTP", "URL"]
#   errcheck:
#     exclude-functions:
#       - (*os.File).Close

linters:
  default: fast
  enable:
    - errcheck
    - revive
  disable:
    - depguard
    - wsl

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-use-default: false
